[package]
name = "flow8-ble"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
btleplug.workspace = true
futures-util.workspace = true
flow8-protocol = { path = "../flow8-protocol" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
flow8-directhci = { path = "../flow8-directhci" }
windows-collections = "0.3"
windows = { version = "0.62", features = [
    "Devices_Bluetooth",
    "Devices_Bluetooth_GenericAttributeProfile",
    "Devices_Enumeration",
    "Foundation",
    "Foundation_Collections",
    "Win32_Devices_Bluetooth",
    "Win32_Devices_DeviceAndDriverInstallation",
    "Win32_Devices_Properties",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
] }

[dev-dependencies]
flow8-core = { path = "../flow8-core" }
flow8-model = { path = "../flow8-model" }
